include(ExternalProject)

SET(FFMPEG_CONFIGURE_COMMAND cd ${SRC_DIR}/FFmpeg-release-6.0 && ./configure --enable-pic --disable-x86asm --prefix=${CMAKE_INSTALL_PREFIX})
SET(FFMPEG_BUILD_COMMAND cd ${SRC_DIR}/FFmpeg-release-6.0 && make)
SET(FFMPEG_INSTALL_COMMAND cd ${SRC_DIR}/FFmpeg-release-6.0 && make install)

ExternalProject_Add(ffmpeg
  INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
  SOURCE_DIR  ${SRC_DIR}/FFmpeg-release-6.0
  # CONFIGURE_COMMAND ${CMAKE_COMMAND}
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/ffmpeg
  CONFIGURE_COMMAND ${FFMPEG_CONFIGURE_COMMAND}
  BUILD_COMMAND ${FFMPEG_BUILD_COMMAND}
  INSTALL_COMMAND ${FFMPEG_INSTALL_COMMAND}
  # INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install
  )