include(ExternalProject)

SET(SDL_CONFIGURE_COMMAND cd ${SRC_DIR}/SDL-release-2.28.0 && ./configure --disable-x86asm --prefix=${CMAKE_INSTALL_PREFIX})
SET(SDL_BUILD_COMMAND cd ${SRC_DIR}/SDL-release-2.28.0 && make)
SET(SDL_INSTALL_COMMAND cd ${SRC_DIR}/SDL-release-2.28.0 && make install)

ExternalProject_Add(sdl
  INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
  SOURCE_DIR  ${SRC_DIR}/SDL-release-2.28.0
  # CONFIGURE_COMMAND ${CMAKE_COMMAND}
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/sdl
  CONFIGURE_COMMAND ${SDL_CONFIGURE_COMMAND}
  BUILD_COMMAND ${SDL_BUILD_COMMAND}
  INSTALL_COMMAND ${SDL_INSTALL_COMMAND}
  # INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install
  )