/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111283-g9b6d191a66-20230629"
#endif /* AVUTIL_FFVERSION_H */
