#ifndef _PLAYER_ERRORS_H_
#define _PLAYER_ERRORS_H_

#define PLAYER_SUSSES 0
#define PLAYER_GLOBAL_INIT_ERROR 1
#define PLAYER_PLAY_WINDOW_ERROR 2
#define PLAYER_PLAY_VIDEO_STATE_ERROR 3
#define PLAYER_PLAY_REFRESH_THREAD_ERROR 4

#endif // _PLAYER_ERRORS_H_